### ISSUE TITLE
evaluation data

### ISSUE THREAD

**Issue by xiehou-design** [ZeroNLP/Clean_LaVe#1]
您好，看了您的论文深受启发，想仔细阅读您的代码，并添加到我当前的工作中，但是我发现数据集好像未提供（也未提供数据集处理的方式），如果方便的话可不可可以告知我数据集处理的方式（或者数据集的获取方式），如事件论元抽取中的`ace.json`。谢谢！

Hello, I have been inspired by your paper and would like to carefully read your code and add it to my current work. However, I have found that the dataset does not seem to be provided (nor does it provide a way to process the dataset). If possible, could you please inform me of the method of processing the dataset (or how to obtain the dataset), such as' ace. json 'in event argument extraction. Thank you!!!

```
DATASET="ace"  
MODE="test"        
run_evaluation_path="/data/jwwang/URE_EAE/ace_dy/Dnorelation/"${MODE}".json" 
```

**Comment by wjw136** [comment]
Thank you for your interest in our work. We have released a pre-processed dataset on https://huggingface.co/datasets/wjwilliam/Clean_LaVe to ensure reproducibility.
